% R: cell array
function CwSaveAsDotD3difo(DotD3difoFilePath, R, KddParam)

    fid = fopen(DotD3difoFilePath, 'wt', 'native', 'US-ASCII');
    if fid == -1
        error('fail to open file for write: %s', DotD3difoFilePath);
    end
    
    fprintf(fid, '%d\n%d\n%s\n%d\n', ...
        KddParam.rutype, KddParam.octype, KddParam.ictype, length(R));

    for i = 1: length(R)
        %save
        fprintf(fid, '%+3d  %+e %+e %+e  %+e  %+e %+e %+e %+e %+e %+e  %s\n', ...
            R{i}.CollimatorType, ...
            R{i}.ShotSpotX, ...
            R{i}.ShotSpotY, ...
            R{i}.ShotSpotZ - KddParam.ziboc_kdd, ...    %convert to OC-Coord
            R{i}.Signature.RefDose, ...
			R{i}.DoseRegionBox.xmin, ...
			R{i}.DoseRegionBox.xmax, ...
			R{i}.DoseRegionBox.ymin, ...
			R{i}.DoseRegionBox.ymax, ...
			R{i}.DoseRegionBox.zmin, ...
			R{i}.DoseRegionBox.zmax, ...
            R{i}.D3dFileName);
    end

    fclose(fid);
end
