% R: cell array
function CwSaveAsDotD3dVrf(DotD3dVrfFilePath, R, KddParam)

    fid = fopen(DotD3dVrfFilePath, 'wt', 'native', 'US-ASCII');
    if fid == -1
        error('fail to open file for write: %s', DotD3dVrfFilePath);
    end
    
    fprintf(fid, '%d\n%d\n%s\n%d\n', ...
        KddParam.rutype, KddParam.octype, KddParam.ictype, length(R));

    for i = 1: length(R)
        %save
        fprintf( fid, '%s %d %e %e %e %e %e %e %e %e %e %e %e %e %e\n', ...
            R{i}.Dot3ddoseFileName, ...
            R{i}.CollimatorType, ...
            R{i}.ShotSpotX, ...
            R{i}.ShotSpotY, ...
            R{i}.ShotSpotZ, ...    %kdd-Coord
            R{i}.Signature.OuterCupSig(:), ...
            R{i}.Signature.InnerCupSig(:), ...
            R{i}.Signature.CollimatorSize, ...
            R{i}.Signature.RefDose, ...
            R{i}.Signature.ShotSpotDose, ...
            R{i}.Signature.MinDose, ...
            R{i}.Signature.MaxDoseIn, ...
            R{i}.Signature.MaxDoseOut, ...
            R{i}.Signature.MaxGradientIn, ...
            R{i}.Signature.MaxGradientOut ...
            );
    end

    fclose(fid);
end

